package pe.com.sedapal.agc.servicio;import java.util.List;


import pe.com.sedapal.agc.model.ProgramaValores;
import pe.com.sedapal.agc.model.Rendimientos;
import pe.com.sedapal.agc.model.RepoCumpActiCierre;
import pe.com.sedapal.agc.model.RepoCumpActiInsp;
import pe.com.sedapal.agc.model.RepoCumpActiNoti;
import pe.com.sedapal.agc.model.RepoCumpActiReapertura;
import pe.com.sedapal.agc.model.RepoCumpActiReci;
import pe.com.sedapal.agc.model.RepoCumpCicloLector;
import pe.com.sedapal.agc.model.RepoEfecActiAvisCob;
import pe.com.sedapal.agc.model.RepoEfecActiTomaEst;
import pe.com.sedapal.agc.model.RepoEfecApertura;
import pe.com.sedapal.agc.model.RepoEfecCierre;
import pe.com.sedapal.agc.model.RepoEfecInspeComer;
import pe.com.sedapal.agc.model.RepoEfecInspeInt;
import pe.com.sedapal.agc.model.RepoEfecLectorTomaEst;
import pe.com.sedapal.agc.model.RepoEfecNotificaciones;
import pe.com.sedapal.agc.model.RepoEfecSostenibilidad;
import pe.com.sedapal.agc.model.RepoInfActiEjec;
import pe.com.sedapal.agc.model.request.ReportesRequest;
import pe.com.sedapal.agc.model.response.Error;

public interface IReportesServicio {
	List<RepoInfActiEjec> obtenerListaRepoInfActiEjec(ReportesRequest request);
	Error getError();
//	void cleanError();
	String generarReporteInfActiEjec(List<RepoInfActiEjec> detalle);
	List<String> obtenerPeriodos();
	String generarExcel(List<RepoInfActiEjec> detalle);
	String generarReporteInfActiEjecCons(List<RepoInfActiEjec> detalle);
	List<String> obtenerUsuarios(ReportesRequest request);
	List<String> obtenerSubactividades(ReportesRequest request);
	List<ProgramaValores> crearProgramaValores(ProgramaValores request);
	List<ProgramaValores> eliminarProgramaValores(ProgramaValores request);
	Integer updateProgramaValores(ProgramaValores request);
	List<ProgramaValores> listarProgramaValores(ProgramaValores request);
	List<Rendimientos> listarRendimientos(Rendimientos request);
	String crearRendimientos(Rendimientos request);
	Integer updateRendimientos(Rendimientos request);
	List<Rendimientos> eliminarRendimientos(Rendimientos request);
	List<RepoEfecActiTomaEst> obtenerListaRepoEfecActiTomaEst(ReportesRequest request);
	String generarRepoEfecActiTomaEst(List<RepoEfecActiTomaEst> detalle);
	String generarRepoEfecActiTomaEstExcel(List<RepoEfecActiTomaEst> detalle);
	List<String> obtenerCiclos(String periodo);
	List<RepoEfecLectorTomaEst> obtenerListaRepoEfecLectorTomaEst(ReportesRequest request);
	String generarRepoEfecLectorTomaEst(List<RepoEfecLectorTomaEst> detalle);
	String generarRepoEfecLectorTomaEstExcel(List<RepoEfecLectorTomaEst> detalle);
	List<RepoEfecNotificaciones> obtenerListaRepoEfecNotificaciones(ReportesRequest request);
	String generarRepoEfecNotificaciones(List<RepoEfecNotificaciones> detalle);
	String generarRepoEfecNotificacionesExcel(List<RepoEfecNotificaciones> detalle);
	String generarRepoEfecInspeComerExcel(List<RepoEfecInspeComer> detalle);
	String generarRepoEfecInspeComer(List<RepoEfecInspeComer> detalle);
	List<RepoEfecInspeComer> obtenerListaRepoEfecInspeComer(ReportesRequest request);
	List<RepoEfecActiAvisCob> obtenerListaRepoEfecActiAvisCob(ReportesRequest request);
	String generarRepoEfecActiAvisCob(List<RepoEfecActiAvisCob> detalle);
	String generarRepoEfecActiAvisCobExcel(List<RepoEfecActiAvisCob> detalle);
	List<RepoEfecInspeInt> obtenerListaRepoEfecInspeInt(ReportesRequest request);
	String generarRepoEfecInspeInt(List<RepoEfecInspeInt> detalle);
	String generarRepoEfecInspeIntExcel(List<RepoEfecInspeInt> detalle);
	List<RepoEfecCierre> obtenerListaRepoEfecCierre(ReportesRequest request);
	String generarRepoEfecCierre(List<RepoEfecCierre> detalle);
	String generarRepoEfecCierreExcel(List<RepoEfecCierre> detalle);
	List<RepoEfecApertura> obtenerListaRepoEfecApertura(ReportesRequest request);
	String generarRepoEfecApertura(List<RepoEfecApertura> detalle);
	String generarRepoEfecAperturaExcel(List<RepoEfecApertura> detalle);
	List<RepoEfecSostenibilidad> obtenerListaRepoEfecSostenibilidad(ReportesRequest request);
	String generarRepoEfecSostenibilidad(List<RepoEfecSostenibilidad> detalle);
	String generarRepoEfecSostenibilidadExcel(List<RepoEfecSostenibilidad> detalle);
	List<RepoCumpCicloLector> obtenerListaRepoCumpCicloLector(ReportesRequest request);
	String generarRepoCumpCicloLector(List<RepoCumpCicloLector> detalle);
	String generarRepoCumpCicloLectorExcel(List<RepoCumpCicloLector> detalle);
	List<RepoCumpActiNoti> obtenerListaRepoCumpActiNoti(ReportesRequest request);
	String generarRepoCumpActiNoti(List<RepoCumpActiNoti> detalle);
	String generarRepoCumpActiNotiExcel(List<RepoCumpActiNoti> detalle);
	List<RepoCumpActiReci> obtenerListaRepoCumpActiReci(ReportesRequest request);
	String generarRepoCumpActiReci(List<RepoCumpActiReci> detalle);
	String generarRepoCumpActiReciExcel(List<RepoCumpActiReci> detalle);
	List<RepoCumpActiInsp> obtenerListaRepoCumpActiInsp(ReportesRequest request);
	String generarRepoCumpActiInsp(List<RepoCumpActiInsp> detalle);
	String generarRepoCumpActiInspExcel(List<RepoCumpActiInsp> detalle);
	List<RepoCumpActiCierre> obtenerListaRepoCumpActiCierre(ReportesRequest request);
	String generarRepoCumpActiCierre(List<RepoCumpActiCierre> detalle);
	String generarRepoCumpActiCierreExcel(List<RepoCumpActiCierre> detalle);
	List<RepoCumpActiReapertura> obtenerListaRepoCumpActiReapertura(ReportesRequest request);
	String generarRepoCumpActiReapertura(List<RepoCumpActiReapertura> detalle);
	String generarRepoCumpActiReaperturaExcel(List<RepoCumpActiReapertura> detalle);
	List<String> obtenerTipoInspe();
	List<String> obtenerItems(String oficina);
	List<String> obtenerActividades(Long item);
	List<String> obtenerSubactividades(Long item, String actividad);
	List<RepoEfecNotificaciones> obtenerListaRepoCumpNotificaciones(ReportesRequest request);
	String generarRepoCumpNotificaciones(List<RepoEfecNotificaciones> detalle);
	String generarRepoCumpNotificacionesExcel(List<RepoEfecNotificaciones> detalle);
	List<String> obtenerFrecAlerta();
}
