package pe.com.sedapal.agc.servicio.impl;

import java.text.ParseException;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import pe.com.sedapal.agc.dao.IInspeccionesComercialesDAO;
import pe.com.sedapal.agc.model.InspeccionesComerciales;
import pe.com.sedapal.agc.model.request.PageRequest;
import pe.com.sedapal.agc.model.response.Error;
import pe.com.sedapal.agc.model.response.Paginacion;
import pe.com.sedapal.agc.servicio.IInspeccionesComercialesService;

@Service
public class InspeccionesComercialesServiceImpl implements IInspeccionesComercialesService {

	@Autowired
	private IInspeccionesComercialesDAO dao;

	@Override
	public List<InspeccionesComerciales> ListarInspeccionesComerciales(PageRequest pageRequest, String V_IDCARGA, Long N_IDREG, Integer V_N_CON_ADJ) throws Exception {
		return dao.ListarInspeccionesComerciales(pageRequest, V_IDCARGA, N_IDREG, V_N_CON_ADJ);
	}
	@Override
	public Paginacion getPaginacion() {
		return this.dao.getPaginacion();
	}
	@Override
	public Error getError() {
		return this.dao.getError();
	}
	
	@Override
	public Map<String, Object> modificarInspComLine(Map<String, String> requestParm) throws ParseException, Exception {
		InspeccionesComerciales ic = new InspeccionesComerciales();
		String sCodigoCarga = requestParm.get("codigoCarga");
		String sCodigoActividad = requestParm.get("codigoActividad");
		String sVar_act_predio = requestParm.get("var_act_predio");
		String sValv_s_p = requestParm.get("valv_s_p ");
		String sValv_e_tlsc = requestParm.get("valv_e_tlsc ");
		String sUu_ocup = requestParm.get("uu_ocup ");
		String sUu_docup = requestParm.get("uu_docup ");
		String sUso_unic = requestParm.get("uso_unic ");
		String sUrin_f = requestParm.get("urin_f ");
		String sUrin_cl = requestParm.get("urin_cl ");
		String sUrin_b = requestParm.get("urin_b ");
		String sUrb_c = requestParm.get("urb_c ");
		String sTip_suelo_des = requestParm.get("tip_suelo_des ");
		String sTip_mat_tub_d = requestParm.get("tip_mat_tub_d ");
		String sTip_mat_tap_d = requestParm.get("tip_mat_tap_d ");
		String sTip_mat_caj_d = requestParm.get("tip_mat_caj_d ");
		String sTip_des_des = requestParm.get("tip_des_des ");
		String sTelf_emp = requestParm.get("telf_emp ");
		String sTelef = requestParm.get("telef ");
		String sTanqu_f = requestParm.get("tanqu_f ");
		String sTanqu_cl = requestParm.get("tanqu_cl ");
		String sTanqu_b = requestParm.get("tanqu_b ");
		String sSoc_ocup = requestParm.get("soc_ocup ");
		String sSoc_desc = requestParm.get("soc_desc ");
		String sSis_trat_res = requestParm.get("sis_trat_res ");
		String sSilo = requestParm.get("silo ");
		String sServDT = requestParm.get("servDT ");
		String sServ = requestParm.get("serv");
		String sSeguro_tap = requestParm.get("seguro_tap ");
		String sSector_f = requestParm.get("sector_f ");
		String sRuc = requestParm.get("ruc ");
		String sRef_c = requestParm.get("ref_c ");
		String sRazsoc = requestParm.get("razsoc ");
		String sProf_cja_des = requestParm.get("prof_cja_des ");
		String sPred_no_ubic = requestParm.get("pred_no_ubic ");
		String sPrescinto = requestParm.get("prescinto ");
		String sPiso_dpto_f = requestParm.get("piso_dpto_f ");
		String sPisc_f = requestParm.get("pisc_f ");
		String sPisc_cl = requestParm.get("pisc_cl ");
		String sPisc_b = requestParm.get("pisc_b ");
		String sPaterno = requestParm.get("paterno");
		String sObservm2 = requestParm.get("observm2 ");
		String sObservm1 = requestParm.get("observm1 ");
		String sObserv = requestParm.get("observ ");
		String sObs_atendio = requestParm.get("obs_atendio ");
		String sNum_med = requestParm.get("num_med ");
		String sNum_c = requestParm.get("num_c ");
		String sNse_f = requestParm.get("nse_f ");
		String sNombre = requestParm.get("nombre ");
		String sNiv_finc = requestParm.get("niv_finc ");
		String sNroConexiones = requestParm.get("nroConexiones");
		String sMza_c = requestParm.get("mza_c ");
		String sMot_no_ing = requestParm.get("mot_no_ing ");
		String sMnto_cartog = requestParm.get("mnto_cartog ");
		String sMedidorEncontrado3 = requestParm.get("medidorEncontrado3");
		String sMedidorEncontrado2 = requestParm.get("medidorEncontrado2");
		String sMaterno = requestParm.get("materno ");
		String sMat_valv_s = requestParm.get("mat_valv_s ");
		String sMat_valv_e = requestParm.get("mat_valv_e ");
		String sLote_c = requestParm.get("lote_c ");
		String sLong_cnx_des = requestParm.get("long_cnx_des ");
		String sLec_med3 = requestParm.get("lec_med3 ");
		String sLec_med2 = requestParm.get("lec_med2 ");
		String sLecturaMedidor = requestParm.get("lecturaMedidor");
		String sLava_f = requestParm.get("lava_f ");
		String sLava_cl = requestParm.get("lava_cl ");
		String sLava_b = requestParm.get("lava_b ");
		String sInspec_realiz = requestParm.get("inspec_realiz ");
		String sInod_f = requestParm.get("inod_f ");
		String sInod_cl = requestParm.get("inod_cl ");
		String sInod_b = requestParm.get("inod_b");
		String sInd_tram_des = requestParm.get("ind_tram_des ");
		String sInd_ocup = requestParm.get("ind_ocup ");
		String sInd_desc = requestParm.get("ind_desc ");
		String sInci_medidor = requestParm.get("inci_medidor ");
		String sImposibilidad = requestParm.get("imposibilidad ");
		String sHora_i = requestParm.get("hora_i ");
		String sHora_f = requestParm.get("hora_f ");
		String sGrifo_f = requestParm.get("grifo_f ");
		String sGrifo_cl = requestParm.get("grifo_cl ");
		String sGrifo_b = requestParm.get("grifo_b ");
		String sEstMedidorEncontrado1 = requestParm.get("estMedidorEncontrado1");
		String sFugaCaja = requestParm.get("fugaCaja ");
		String sFte_conexion_c = requestParm.get("fte_conexion_c ");
		String sFte_conexion = requestParm.get("fte_conexion ");
		String sFechaVisita = requestParm.get("fechaVisita");
		String sFax = requestParm.get("fax ");
		String sEstado = requestParm.get("estado ");
		String sEst_tub_des = requestParm.get("est_tub_des ");
		String sEst_tapa_des = requestParm.get("est_tapa_des ");
		String sEst_tapa = requestParm.get("est_tapa ");
		String sEst_ocup = requestParm.get("est_ocup ");
		String sEst_desc = requestParm.get("est_desc ");
		String sEst_caja_des = requestParm.get("est_caja_des ");
		String sEstadoCaja = requestParm.get("estadoCaja");
		String sEmail = requestParm.get("email ");
		String sDupli_c = requestParm.get("dupli_c ");
		String sDuch_f = requestParm.get("duch_f ");
		String sDuch_cl = requestParm.get("duch_cl ");
		String sDuch_b = requestParm.get("duch_b ");
		String sDom_ocup = requestParm.get("dom_ocup ");
		String sDom_desc = requestParm.get("dom_desc ");
		String sDni = requestParm.get("dni ");
		String sDist_c = requestParm.get("dist_c ");
		String sDisposit = requestParm.get("disposit ");
		String sDia_med3 = requestParm.get("dia_med3 ");
		String sDia_med2 = requestParm.get("dia_med2");
		String sDia_med = requestParm.get("dia_med ");
		String sDia_conex_des = requestParm.get("dia_conex_des ");
		String sDia_conex_agua = requestParm.get("dia_conex_agua");
		String sCota_ver_des = requestParm.get("cota_ver_des ");
		String sCota_sum_c = requestParm.get("cota_sum_c ");
		String sCota_hor_des = requestParm.get("cota_hor_des ");
		String sCorr_cup = requestParm.get("corr_cup ");
		String sCom_ocup = requestParm.get("com_ocup ");
		String sCom_desc = requestParm.get("com_desc ");
		String sCod_ubic = requestParm.get("cod_ubic");
		String sCod_sup = requestParm.get("cod_sup ");
		String sCodEmpleado = requestParm.get("codEmpleado");
		String sCod_digit = requestParm.get("cod_digit ");
		String sCnx3_con = requestParm.get("cnx3_con ");
		String sCnx2_con = requestParm.get("cnx2_con ");
		String sCnxCon = requestParm.get("cnxCon ");
		String sClandes_des = requestParm.get("clandes_des ");
		String sClandes = requestParm.get("clandes ");
		String sCiste_f = requestParm.get("ciste_f ");
		String sCiste_cl = requestParm.get("ciste_cl ");
		String sCiste_b = requestParm.get("ciste_b ");
		String sCel_cli_c = requestParm.get("cel_cli_c ");
		String sCartografia = requestParm.get("cartografia ");
		String sCalle_c = requestParm.get("calle_c ");
		String sCaja = requestParm.get("caja");
		String sBidet_f = requestParm.get("bidet_f ");
		String sBidet_cl = requestParm.get("bidet_cl ");
		String sBidet_b = requestParm.get("bidet_b");
		String sAtendio = requestParm.get("atendio ");
		String sAbast = requestParm.get("abast");
		String sUsuario = requestParm.get("usuarioModifica");

		ic.setCodigoCarga(sCodigoCarga);
		ic.setCodigoRegistro(Integer.parseInt(sCodigoActividad));
		ic.setVar_act_predio(sVar_act_predio);
		ic.setValv_s_p(sValv_s_p);
		ic.setValv_e_tlsc(sValv_e_tlsc);
		ic.setUu_ocup(sUu_ocup);
		ic.setUu_docup(sUu_docup);
		ic.setUso_unic(sUso_unic);
		ic.setUrin_f(sUrin_f);
		ic.setUrin_cl(sUrin_cl);
		ic.setUrin_b(sUrin_b);
		ic.setUrb_c(sUrb_c);
		ic.setTip_suelo_des(sTip_suelo_des);
		ic.setTip_mat_tub_d(sTip_mat_tub_d);
		ic.setTip_mat_tap_d(sTip_mat_tap_d);
		ic.setTip_mat_caj_d(sTip_mat_caj_d);
		ic.setTip_des_des(sTip_des_des);
		ic.setTelf_emp(Integer.parseInt(sTelf_emp));
		ic.setTelef(sTelef);
		ic.setTanqu_f(sTanqu_f);
		ic.setTanqu_cl(sTanqu_cl);
		ic.setTanqu_b(sTanqu_b);
		ic.setSoc_ocup(sSoc_ocup);
		ic.setSoc_desc(sSoc_desc);
		ic.setSis_trat_res(sSis_trat_res);
		ic.setSilo(sSilo);
		ic.setServDT(sServDT);
		ic.setServ(sServ);
		ic.setSeguro_tap(sSeguro_tap);
		ic.setSector_f(Integer.parseInt(sSector_f));
		ic.setRuc(sRuc);
		ic.setRef_c(sRef_c);
		ic.setRazsoc(sRazsoc);
		ic.setProf_cja_des(Double.parseDouble(sProf_cja_des));
		ic.setPred_no_ubic(sPred_no_ubic);
		ic.setPrescinto(sPrescinto);
		ic.setPiso_dpto_f(sPiso_dpto_f);
		ic.setPisc_f(sPisc_f);
		ic.setPisc_cl(sPisc_cl);
		ic.setPisc_b(sPisc_b);
		ic.setPaterno(sPaterno);
		ic.setObservm2(sObservm2);
		ic.setObservm1(sObservm1);
		ic.setObserv(sObserv);
		ic.setObs_atendio(sObs_atendio);
		ic.setNum_med(sNum_med);
		ic.setNum_c(sNum_c);
		ic.setNse_f(sNse_f);
		ic.setNombre(sNombre);
		ic.setNiv_finc(sNiv_finc);
		ic.setNroConexiones(sNroConexiones);
		ic.setMza_c(sMza_c);
		ic.setMot_no_ing(sMot_no_ing);
		ic.setMnto_cartog(sMnto_cartog);
		ic.setMedidorEncontrado3(sMedidorEncontrado3);
		ic.setMedidorEncontrado2(sMedidorEncontrado2);
		ic.setMaterno(sMaterno);
		ic.setMat_valv_s(sMat_valv_s);
		ic.setMat_valv_e(sMat_valv_e);
		ic.setLote_c(sLote_c);
		ic.setLong_cnx_des(Double.parseDouble(sLong_cnx_des));
		ic.setLec_med3(Integer.parseInt(sLec_med3));
		ic.setLec_med2(Integer.parseInt(sLec_med2));
		ic.setLecturaMedidor(sLecturaMedidor);
		ic.setLava_f(sLava_f);
		ic.setLava_cl(sLava_cl);
		ic.setLava_b(sLava_b);
		ic.setInspec_realiz(sInspec_realiz);
		ic.setInod_f(sInod_f);
		ic.setInod_cl(sInod_cl);
		ic.setInod_b(sInod_b);
		ic.setInd_tram_des(sInd_tram_des);
		ic.setInd_ocup(sInd_ocup);
		ic.setInd_desc(sInd_desc);
		ic.setInci_medidor(sInci_medidor);
		ic.setImposibilidad(sImposibilidad);
		ic.setHora_i(sHora_i);
		ic.setHora_f(sHora_f);
		ic.setGrifo_f(sGrifo_f);
		ic.setGrifo_cl(sGrifo_cl);
		ic.setGrifo_b(sGrifo_b);
		ic.setEstMedidorEncontrado1(sEstMedidorEncontrado1);
		ic.setFugaCaja(sFugaCaja);
		ic.setFte_conexion_c(sFte_conexion_c);
		ic.setFte_conexion(sFte_conexion);
		ic.setFechaVisita(sFechaVisita);
		ic.setFax(sFax);
		ic.setEstado(sEstado);
		ic.setEst_tub_des(sEst_tub_des);
		ic.setEst_tapa_des(sEst_tapa_des);
		ic.setEst_tapa(sEst_tapa);
		ic.setEst_ocup(sEst_ocup);
		ic.setEst_desc(sEst_desc);
		ic.setEst_caja_des(sEst_caja_des);
		ic.setEstadoCaja(sEstadoCaja);
		ic.setEmail(sEmail);
		ic.setDupli_c(sDupli_c);
		ic.setDuch_f(sDuch_f);
		ic.setDuch_cl(sDuch_cl);
		ic.setDuch_b(sDuch_b);
		ic.setDom_ocup(sDom_ocup);
		ic.setDom_desc(sDom_desc);
		ic.setDni(sDni);
		ic.setDist_c(sDist_c);
		ic.setDisposit(sDisposit);
		ic.setDia_med3(sDia_med3);
		ic.setDia_med2(sDia_med2);
		ic.setDia_med(sDia_med);
		ic.setDia_conex_des(sDia_conex_des);
		ic.setDia_conex_agua(Double.parseDouble(sDia_conex_agua));
		ic.setCota_ver_des(Double.parseDouble(sCota_ver_des));
		ic.setCota_sum_c(sCota_sum_c);
		ic.setCota_hor_des(Double.parseDouble(sCota_hor_des));
		ic.setCorr_cup(sCorr_cup);
		ic.setCom_ocup(sCom_ocup);
		ic.setCom_desc(sCom_desc);
		ic.setCod_ubic(sCod_ubic);
		ic.setCod_sup(Integer.parseInt(sCod_sup));
		ic.setCodEmpleado(sCodEmpleado);
		ic.setCod_digit(Integer.parseInt(sCod_digit));
		ic.setCnx3_con(sCnx3_con);
		ic.setCnx2_con(sCnx2_con);
		ic.setCnxCon(sCnxCon);
		ic.setClandes_des(sClandes_des);
		ic.setClandes(sClandes);
		ic.setCiste_f(sCiste_f);
		ic.setCiste_cl(sCiste_cl);
		ic.setCiste_b(sCiste_b);
		ic.setCel_cli_c(Double.parseDouble(sCel_cli_c));
		ic.setCartografia(sCartografia);
		ic.setCalle_c(sCalle_c);
		ic.setCaja(sCaja);
		ic.setBidet_f(sBidet_f);
		ic.setBidet_cl(sBidet_cl);
		ic.setBidet_b(sBidet_b);
		ic.setAtendio(sAtendio);
		ic.setAbast(sAbast);		
		return dao.actualizarDistComLine(ic, sUsuario);
	}

}
